```{r 01_setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=FALSE)
```

# (PART) Foundational Ideas {-}

# Motivation and Review

Slides from today are available [here](https://docs.google.com/presentation/d/1GbDZ1OyeAC1VvwNwprxDXi4UV7jvFB1Lsw_HWbgoegw/edit?usp=sharing).

<br><br>

## Discussion prompts {-}

**Reminder:** Make note of both your gut reactions and those of your peers. Today is all about ***noticing*** the subtle and unconcious ways that we think about causation, so these gut reactions are treasures worth capturing!

As you discuss, add these noticings and your thoughts to the prompts to [this Google Doc](https://docs.google.com/document/d/1-4V4JbmrJ3wnXIBoLcBWkSnYCQh3aJm7Bs9geI_VNvQ/edit?usp=sharing) so that we have a shared class resource.

<br>

### Considering causes {-}

Given that we're in a class called ***Causal Inference***, it's worth thinking deeply about the notions of *causes* and *causation*.

- Consider the word "cause" (and related phrases like "results in" and "leads to.") What do you think "cause" means? How do you/people you know use it in day-to-day conversation and thinking?
- Why do we want to learn about causes? What should our goals be in learning about causes?

<br>

### Sinful saying or mandatory mantra? {-}

> Correlation does not imply causation.

- How has this saying come up in conversation for you? How do you feel about the value of this saying?

- Consider the following scenarios. What are your reactions to using this saying in each of them?
    - Days with higher ice cream sales tend to have higher crime rates.
    - Individuals with larger shoe sizes tend to have better reading ability.
    - Individuals who practice meditation tend to experience less stress.
    - Individuals who regularly smoke cigarettes tend to develop lung cancer at higher rates than nonsmokers.

<br>

### Sufficiency and necessity {-}

Consider the following statements:

- If X happens, then Y will happen.
- If X does not happen, then Y will not happen.

Are these statements redundant? (Do they give identical information about X and Y?) Why or why not?

<br>

### Evaluating evidence for causation: Bradford Hill criteria {-}

In 1965, epidemiologist Sir Austin Bradford Hill propsed a set of nine criteria for evaluating evidence for a causal relationship. Let's explore these criteria and reflect on how it fits into our mental frameworks on causation.

Lucy D'Agostino McGowan has a fun [presentation](https://docs.google.com/presentation/d/1rSZ4Momsr_sVcvNncgpS1NDqevlmCeXDPzHtLDv-xOs/edit#slide=id.gb9bfbb7b4c_0_9) that explains Hill's criteria through [XKCD](https://xkcd.com) comics. What criteria do you find most/least compelling?


