# Guiding Questions {-}

**Motivation and Review** <a id="gq-motivation-review"></a>

- Let's think about the word "cause" (and related phrases like "results in" and "leads to.") What do you think "cause" means? How do you/people you know use it in day-to-day conversation and thinking?
- Why do we want to learn about causes? What should our goals be in learning about causes?
- "Correlation does not imply causation." Has this saying come up in conversations occasionally? If so, how? How do you feel about the value of this saying?

<br><br><br><br><br>

**Exchangeability** <a id="gq-exchangeability"></a>

- Is the definition of a potential outcome and a causal effect satisfying to you? How do these notions relate to what you had thought about causes and causation previously? (Reflect on and connect to our Day 1 activity.)
- Let's think about exchangeability in big picture terms. Setting aside the technical definitions in terms of (conditional) independence, what is exchangeability trying to describe? Try to find a good word/phrase (not "independent") to complete the following sentence: "If the treated and untreated groups are exchangeable, we could also describe them as being ..."
- How can we use the concepts of marginal and conditional exchangeability to make statements about potential outcome distributions in the treated and in the untreated?
- Marginal and conditional exchangeability are **assumptions**--do you think these assumptions are testable using data? Why or why not?

Extra self-check resource: Moodle checkpoint on [Causal Effects and Exchangeability](https://moodle.macalester.edu/mod/quiz/view.php?id=17844)

<br><br><br><br><br>

**Study Designs** <a id="gq-study-designs"></a>

- Why are randomized experiments often called the "gold standard" for causal inference? What is the relationship between randomized experiments and exchangeability?
- Consider the quasi-experimental designs discussed in the video. How do these designs try to mimic randomization? What assumptions do they make to allow making statements about missing potential outcomes?

Extra self-check resource: Moodle checkpoint on [Study Designs for Causal Inference](https://moodle.macalester.edu/mod/quiz/view.php?id=17845)

<br><br><br><br><br>

**Causal Graphs as Statistical Models** <a id="gq-causal-graphs-models"></a>

- Why is it sensible for causal graphs to be directed and acyclic?
- How can "feedback loops" be represented in causal graphs?
- What extra information does a structural equation model encode that a causal graph alone does not?

Extra self-check resource: Moodle checkpoint on [Causal Graphs as Statistical Models](https://moodle.macalester.edu/mod/quiz/view.php?id=17846)

<br><br><br><br><br>

**Key Structures in Causal Graphs** <a id="gq-key-structures"></a>

- What marginal and conditional (in)dependence relations pertain to chains, forks, and colliders? Do these relations make sense? What examples (in the video or your own) help rationalize these relations?

Extra self-check resource: Moodle checkpoint on [Key Structures in Causal Graphs](https://moodle.macalester.edu/mod/quiz/view.php?id=17847)

<br><br><br><br><br>

**Graphical Structure of Confounding** <a id="gq-struct-confounding"></a>

- 

Extra self-check resource: Moodle checkpoint on [(Non)causal Paths and D-Separation](https://moodle.macalester.edu/mod/quiz/view.php?id=17848)

<br><br><br><br><br>

**Graphical Structure of Selection Bias** <a id="gq-struct-selection-bias"></a>

- 

<br><br><br><br><br>

**The Smoking-Birthweight Paradox** <a id="gq-sbw-paradox"></a>

- 

<br><br><br><br><br>

**The Smoking-Birthweight Paradox: Alternate Explanations** <a id="gq-sbw-paradox-alt"></a>

- 

<div style="height: 600px;"></div>
