```{r hw2_setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=FALSE)
```

# Homework 2 {-}

## General instructions {-}

Due: Friday, February 3 at midnight CST.

- Continue using the same Google Doc from HW1.


<br><br>


## Revisions {-}

If you would like to make revisions to any parts of Homework 1, please do the following:

- Keep all old writing and feedback intact
- Write an updated response just below your previous response and highlight the new writing in yellow


<br><br>


## Part 1 {-}

Chains, forks, and colliders in causal graphs are the building blocks for causal graphs and the stepping stones for understanding how bias arises when estimating causal effects.

a. What ideas from Topics 4 and 5 (Causal Graphs as Statistical Models and Key Structures in Causal Graphs) would you categorize as an Enduring Concept, Important Concept, or a Concept Worth Being Familiar With? Why? (Refer to our syllabus for descriptions of these concept types.)

b. Write your own explanation for the intuition behind the marginal and conditional (in)dependence relations in chains, forks, and colliders. Try to use examples that are different from the ones in the pre-class concept videos. Your writing should be accessible to an audience who has not taken Probability.


<br><br>


## Part 2 {-}

Related to course components: Metacognitive Reflection

- Has your level of understanding for the Exchangeability and Study Designs topics changed since Homework 1? If so, how and why?

- How do you feel about your level of understanding Topics 4 and 5 (Causal Graphs as Statistical Models and Key Structures in Causal Graphs)? What were some notable themes in self- and peer-noticings? How do these reflections inform your next steps for developing stronger understanding and/or advising future students learning about these topics?


