```{r project_setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=FALSE)
```

# (PART) Project {-}

# Final Project {-}

My sole hope for this project is for it to ***further your goals*** for taking this course. Let's collaborate to make it a good experience for you.


<br><br><br><br>


## Project Options {-}

### Option 1: Data analysis {-}

<!-- Clarify that this can just be a **PLAN** for a data analysis. Ask questions that you are genuinely interested in and describe what data would need to be collected. -->

**Collaboration:** Groups of up to 3. Individual work is fine.

Perform a causal analysis on a dataset of your choice.

- The methods you use for analysis will vary depending on your research questions and the structure of your data (e.g., different methods for quasi-experimental designs vs. general observational studies).
    - You'll plan your methods in collaboration with the instructor.
- A key part of all analyses will be sensitivity analyses to assess robustness of results to points of uncertainty in the analysis process.

Resources for finding data:

- [Google Dataset Search](https://datasetsearch.research.google.com/)
- [Harvard Dataverse](https://dataverse.harvard.edu/)
- [Inter-university Consortium for Political and Social Research (ICPSR)](https://www.icpsr.umich.edu/)
- [IPUMS](https://ipums.org/)
- Macalester's librarians can also be a great resource for finding data. Schedule an appointment with them [here](https://www.macalester.edu/library/askus/).

<!-- (From https://www.macalester.edu/seriecenter/sample-syllabus-statements-and-policies/#library-resources) -->


<br><br>


### Option 2: Blog posts {-}

**Collaboration:** Individual only.

Write two blog posts explaining causal inference ideas to a general audience.

- Post 1: A Tour of Causal Inference
    - Which of our course ideas resonated most with you?
    - Lead the reader through these topics in an engaging and cohesive way.
- Post 2: Pick any media item that has interested you. Write a reaction to it / an analysis of it from a causal inference perspective.
    - If you're looking to explore some media, the [Casual Inference podcast](https://casualinfer.libsyn.com/) is a fun one!


<br><br>


### Option 3: Learn an advanced topic {-}

**Collaboration:** Groups of up to 3. Individual work is fine.

Dig deeper into existing course topics or learn a new topic. Examples could include:

- Methods for transportability (generalizability) of effects
- Interference
- Details of methods for time-varying treatments
- Specialized considerations for particular study designs
- Doubly-robust estimation


<br><br>


### Option 4: Other {-}

If none of these options piques your interest, I'm happy to discuss alternatives with you. Some ideas:

- Design a Shiny app to illustrate causal concepts to students
- Write (part of) an R package for making it easier to work with causal graphs
- Critique of applied research
    - This is a good option for those who would like to do a data analysis but cannot find adequate data to pursue their question.
    - Find and read papers that study a question of interest to you. Critique these papers from a causal inference lens. This will involve constructing your own causal graph to guide a critique of the authors' data collection and analysis methods.
    - Discuss what remains uncertain in this line of research, and propose an analysis plan for a new causal study to rectify the limitations of prior research.


<br><br><br><br>


## Deliverables {-}

There is a lot of flexibility in the form that your project takes. Examples include:

- A video presentation
- A podcast-style recording
- A set of blog posts
- A project webpage on a personal website

Work with the instructor to determine the most suitable deliverable for your project, depending on the option you pick.


<br><br><br><br>


## Timeline {-}

- **Milestone 1: Project Proposal** Choose your final project option, topic, and group by Friday, March 10 at midnight CST.
    - Data analysis option: Find a dataset and formulate causal question(s) that you want to answer.
    - Blog post option: Outline ideas for one post
    - Advanced topic option: Settle on an advanced topic, and do some preliminary research to identify key ideas within this topic.

<br>

- **Milestone 2:** Friday, March 31
    - Data analysis option: Understand your data context well and construct an initial causal graph.
    - Blog post option: Brainstorm ideas or create an outline for one post.
    - Advanced topic option: Make progress in learning about one sub-area for your topic.
    - Other: Make progress appropriate to the scope of the project.

<br>

- **Milestone 3:** Sunday, April 9 (Check in in-person or via an email exchange)
    - Data analysis option: Finalize your causal graph and construct visualizations to inform an appropriate outcome regression and IPW analysis.
        - Finalizing your causal graph does not require, for example, doing causal discovery by hand. You should think through your graph holistically along the lines of the flow discussed in the [Drawing Causal Diagrams](https://theeffectbook.net/ch-DrawingCausalDiagrams.html) chapter of The Effect (the reading from HW4). You should feel satisfied that you have represented all relevant variables and the relationships between them.
    - Blog post option: Draft Post 1 (A tour of causal inference)
    - Advanced topic option: Make progress in learning about one sub-area for your topic.
    - Other: Make progress appropriate to the scope of the project.

<br>

- **Milestone 4:** Schedule a time to meet with me during class time this week via [Calendly](https://calendly.com/lmyint). (You can choose an in-person or Zoom option on Calendly.)
    - Data analysis option: Based on your visualizations, construct an outcome regression model, and conduct an IPW analysis. Refer to your workflow write-up from HW4 to guide the steps taken here. Organize information on causal effect estimates (overall, and possibly within subgroups, if that is of interest) and confidence intervals.
    - Blog post option: Make substantial progress on Post 1 (A tour of causal inference)
    - Advanced topic option: Make progress in learning about one sub-area for your topic.
    - Other: Make progress appropriate to the scope of the project.

<br>

- **Milestone 5:** Schedule a time to meet with me this week via [Calendly](https://calendly.com/lmyint) to share updates on your progress. (You can choose an in-person or Zoom option on Calendly.)
    - Data analysis option: Conduct a sensitivity analysis for unmeasured confounding for your project, and complete a draft of your deliverable.
    - Blog post option: Finalize Post 1 (A tour of causal inference) and make substantial progress on Post 2.
    - Advanced topic option: Make progress on the goals you set with the instructor in the previous week, and complete a draft of your deliverable.
    - Other: Make progress appropriate to the scope of the project, and complete a draft of your deliverable.

<!-- <br>

- **Milestone 3:** Thursday, October 15 or Friday, October 16. Schedule a discussion time with me on [Google Calendar](https://calendar.google.com/calendar/selfsched?sstoken=UUFBWjVpaTNFb2JUfGRlZmF1bHR8ODFhZGU4ZWQ5MjJkOWY2M2Q4YjZhNTgwN2IyMmFlM2Y).
    - Data analysis option: Come prepared to tell me about the models you've fit and your interpretations. Share a draft of your artifact so far with me 24 hours in advance.
    - Blog post option: Complete full drafts of both posts and share with me 24 hours before our meeting so that I can give feedback and discuss with you.
    - Advanced topic option: Come prepared to tell me more about new material that is the equivalent of the second 5 minutes of a 15 minute presentation. Share a draft of your artifact so far with me 24 hours in advance.

<br>

- **Milestone 4:** Monday, October 19 or Tuesday, October 20. Schedule a discussion time with me on [Google Calendar](https://calendar.google.com/calendar/selfsched?sstoken=UUFBWjVpaTNFb2JUfGRlZmF1bHR8ODFhZGU4ZWQ5MjJkOWY2M2Q4YjZhNTgwN2IyMmFlM2Y).
    - Data analysis option: Come prepared to discuss final points of feedback from the previous meeting (deadline 3). Finalize your artifact draft, and share with me 24 hours in advance.
    - Blog post option: Act on feedback from the previous meeting (deadline 3), and share with me 24 hours before our meeting.
    - Advanced topic option: Come prepared to tell me more about new material that is the equivalent of the last 5 minutes of a 15 minute presentation. Finalize your artifact draft, and share with me 24 hours in advance.

<br>

- **Final deadline:** Friday, October 23. By midnight CST, submit the final version of your digital artifact [on Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=39212).
    - We will not have a showcase/presentation day in class, but instead, I look forward to seeing you showcase your work for the department at either of our two departmental capstone unveiling days! (One will be at the end of Module 2 and the other at the end of Module 4.) -->
