# Schedule {-}

The schedule below is a tentative outline of our plans for the semester. If we need more time for digesting certain topics, we can make space for that.

Before each class period, please watch the indicated videos, complete required readings, and work through the [Guiding Questions](guiding-questions.html). Responses to these questions don't need to be turned in, but there will be many opportunities during class for you to check in with classmates about concepts you found confusing or intriguing.

**Remember to take notes on where you paused/rewound/reread or smiled/nodded during the videos/readings.** This is essential for the **Metacognitive Reflection** part of the course.

Most readings are optional--they complement ideas in the videos by presenting concepts in a different way. (Note that the PRIMER and WHATIF abbreviations refer to free online textbooks listed on the [References](references.html) page.) When a reading is required, it will marked as **(REQD)**.

<br>

```{r echo=FALSE}
htmltools::includeHTML("schedule_table.html")
```